name: Build Custom Kernel CLO (sm8250)

on:
  workflow_dispatch: # Bật tính năng cho phép bác bấm nút "Run workflow" bằng tay trên web

jobs:
  kernel-compiler:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Cài đặt các Package hệ thống phụ trợ
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libncurses6 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
    
    - name: 2. Kéo Source Code của bác về máy ảo
      uses: actions/checkout@v4
      with:
        ref: lineage-tiny # Chạy đúng cái branch bác đã up lên

    - name: 3. Tải và Setup bộ Toolchain ZyC Clang 20+
      run: |
        mkdir -p $GITHUB_WORKSPACE/clang
        cd $GITHUB_WORKSPACE/clang
        # Tải bản Clang 20 ổn định từ release của ZyCromerZ
        wget https://github.com/ZyCromerZ/Clang/releases/download/23.0.0git-20260130-release/Clang-23.0.0git-20260130.tar.gz
        tar -xf Clang-23.0.0git-20260130.tar.gz
        rm Clang-23.0.0git-20260130.tar.gz
        echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH
        

    - name: 4. Tiến hành Compile Nhân Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export HEADER_ARCH=arm64
        export O=out
        make O=out alioth_defconfig
        # Ép Clang và LLVM kết hợp hoàn toàn
        make O=out -j$(nproc) CC=clang LLVM=1 LLVM_IAS=1
        
    - name: 5. Đóng gói sản phẩm AnyKernel3 (Nếu cần) hoặc xuất file Image.gz
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifact
        if [ -f "out/arch/arm64/boot/Image.gz" ]; then
          cp out/arch/arm64/boot/Image.gz $GITHUB_WORKSPACE/artifact/
          echo "==> Build thành công rực rỡ!"
        else
          echo "==> Lỗi rồi, không tìm thấy Image.gz!"
          exit 1
        fi

    - name: 6. Up hàng lên GitHub cho bác tải về máy
      uses: actions/upload-artifact@v4
      with:
        name: Custom-Kernel-Alioth
        path: ${{ github.workspace }}/artifact/*
        
